# app.py
# Phase 8 - Streamlit Dashboard (Professional UI Redesign)
# Remote Maternal Health Monitoring and Escalation System
#
# DISCLAIMER: Educational prototype using simulated and anonymous data.
#             NOT a medical diagnostic system.
#
# Run with:  streamlit run app.py
#
# Required CSV files (generated by Phases 2-7):
#   data/escalation_results.csv  |  data/conflict_results.csv
#   data/cleaned_maternal_data.csv  |  data/trend_results.csv
#   data/demo_conflict_cases.csv

import os
import pandas as pd
import streamlit as st

# ---------------------------------------------------------------------------
# PAGE CONFIG
# ---------------------------------------------------------------------------
st.set_page_config(
    page_title="Maternal Health Monitoring System",
    page_icon="health_worker",
    layout="wide",
    initial_sidebar_state="expanded",
)

# ---------------------------------------------------------------------------
# GLOBAL CSS  –  professional healthcare SaaS style
# ---------------------------------------------------------------------------
st.markdown("""
<style>
/* ---------- fonts & base ---------- */
@import url('https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&display=swap');
html, body, [class*="css"] { font-family: 'Inter', 'Segoe UI', sans-serif; }

/* ---------- hide default Streamlit chrome ---------- */
#MainMenu {visibility:hidden;} footer {visibility:hidden;}
.block-container { padding: 1.4rem 2rem 2rem 2rem !important; }

/* ---------- sidebar ---------- */
section[data-testid="stSidebar"] {
    background: #0f2744;
    color: white;
}
section[data-testid="stSidebar"] * { color: white !important; }
section[data-testid="stSidebar"] .stRadio label { color: #c8d8ec !important; }
section[data-testid="stSidebar"] hr { border-color: #1e3a60; }

/* ---------- page header banner ---------- */
.dash-header {
    background: linear-gradient(120deg, #0f2744 0%, #1a4a8a 60%, #2563c7 100%);
    border-radius: 14px;
    padding: 1.6rem 2rem 1.3rem 2rem;
    margin-bottom: 1.2rem;
    color: white;
}
.dash-header h1 {
    margin: 0 0 0.2rem 0;
    font-size: 1.6rem;
    font-weight: 700;
    color: white;
    line-height: 1.3;
}
.dash-header p {
    margin: 0 0 0.7rem 0;
    font-size: 0.88rem;
    color: #a8c4e8;
}
.status-badge {
    display: inline-flex;
    align-items: center;
    gap: 6px;
    background: rgba(255,255,255,0.12);
    border: 1px solid rgba(255,255,255,0.25);
    border-radius: 20px;
    padding: 3px 12px;
    font-size: 0.78rem;
    color: #90ee90;
    font-weight: 600;
}
.disclaimer-bar {
    background: rgba(255,255,255,0.08);
    border-radius: 6px;
    padding: 5px 12px;
    font-size: 0.73rem;
    color: #a8c4e8;
    margin-top: 0.6rem;
}

/* ---------- section titles ---------- */
.sec-title {
    font-size: 0.78rem;
    font-weight: 700;
    text-transform: uppercase;
    letter-spacing: 0.08em;
    color: #64748b;
    margin: 1.4rem 0 0.7rem 0;
    padding-bottom: 0.4rem;
    border-bottom: 2px solid #e8edf4;
}

/* ---------- KPI cards ---------- */
.kpi-grid { display: flex; gap: 14px; flex-wrap: wrap; margin-bottom: 0.5rem; }
.kpi-card {
    flex: 1; min-width: 130px;
    background: #ffffff;
    border: 1px solid #e4eaf4;
    border-radius: 12px;
    padding: 1.1rem 1.1rem 0.9rem 1.1rem;
    box-shadow: 0 2px 8px rgba(0,0,0,0.05);
    position: relative;
    overflow: hidden;
}
.kpi-card::before {
    content: '';
    position: absolute;
    top: 0; left: 0; right: 0;
    height: 3px;
    background: var(--accent);
}
.kpi-label { font-size: 0.7rem; font-weight: 600; text-transform: uppercase;
             letter-spacing: 0.06em; color: #64748b; margin-bottom: 0.35rem; }
.kpi-value { font-size: 2.1rem; font-weight: 800; color: var(--accent);
             line-height: 1.1; margin-bottom: 0.25rem; }
.kpi-sub   { font-size: 0.71rem; color: #94a3b8; }

/* accent colours per priority */
.kpi-total    { --accent: #2563c7; }
.kpi-critical { --accent: #dc2626; }
.kpi-high     { --accent: #ea580c; }
.kpi-medium   { --accent: #d97706; }
.kpi-low      { --accent: #16a34a; }
.kpi-untrust  { --accent: #6b7280; }
.kpi-blue     { --accent: #2563c7; }
.kpi-green    { --accent: #16a34a; }
.kpi-orange   { --accent: #ea580c; }
.kpi-red      { --accent: #dc2626; }
.kpi-gray     { --accent: #6b7280; }

/* ---------- info / feature cards ---------- */
.info-card {
    background: #ffffff;
    border: 1px solid #e4eaf4;
    border-radius: 12px;
    padding: 1rem 1.1rem;
    box-shadow: 0 2px 8px rgba(0,0,0,0.04);
    height: 100%;
}
.info-card h4 { margin: 0 0 0.3rem 0; font-size: 0.92rem;
                font-weight: 600; color: #1e293b; }
.info-card p  { margin: 0; font-size: 0.8rem; color: #64748b; }

/* ---------- privacy card ---------- */
.privacy-card {
    background: #f0f7ff;
    border: 1px solid #bfdbfe;
    border-radius: 12px;
    padding: 1rem 1.2rem;
}
.privacy-card h4 { margin: 0 0 0.5rem 0; font-size: 0.9rem;
                   font-weight: 700; color: #1e40af; }
.privacy-item { font-size: 0.8rem; color: #1e3a70; margin: 2px 0; }

/* ---------- vital sign boxes ---------- */
.vital-box {
    background: #f8faff;
    border: 1px solid #dbe8f8;
    border-radius: 10px;
    padding: 0.7rem 0.8rem;
    text-align: center;
}
.vital-label { font-size: 0.65rem; font-weight: 600; text-transform: uppercase;
               letter-spacing: 0.05em; color: #64748b; margin-bottom: 4px; }
.vital-value { font-size: 1.45rem; font-weight: 800; color: #0f2744; }
.vital-unit  { font-size: 0.65rem; color: #94a3b8; margin-top: 2px; }

/* ---------- symptom badges ---------- */
.sym-yes { display:inline-block; background:#fef2f2; color:#dc2626;
           border:1px solid #fca5a5; border-radius:6px;
           padding:3px 10px; font-size:0.78rem; font-weight:600; margin:3px; }
.sym-no  { display:inline-block; background:#f0fdf4; color:#16a34a;
           border:1px solid #86efac; border-radius:6px;
           padding:3px 10px; font-size:0.78rem; margin:3px; }

/* ---------- priority & conflict badges ---------- */
.badge {
    display:inline-block; border-radius:6px;
    padding:3px 11px; font-size:0.75rem; font-weight:700;
    letter-spacing:0.04em;
}
.b-critical { background:#fef2f2; color:#dc2626; border:1px solid #fca5a5; }
.b-high     { background:#fff7ed; color:#ea580c; border:1px solid #fdba74; }
.b-medium   { background:#fffbeb; color:#d97706; border:1px solid #fcd34d; }
.b-low      { background:#f0fdf4; color:#16a34a; border:1px solid #86efac; }
.b-untrust  { background:#f9fafb; color:#6b7280; border:1px solid #d1d5db; }
.b-conflict { background:#fef2f2; color:#dc2626; border:1px solid #fca5a5; }
.b-sensor   { background:#fff7ed; color:#ea580c; border:1px solid #fdba74; }
.b-insuff   { background:#f9fafb; color:#6b7280; border:1px solid #d1d5db; }
.b-ok       { background:#f0fdf4; color:#16a34a; border:1px solid #86efac; }

/* ---------- action box ---------- */
.action-critical { background:#fef2f2; border:1px solid #fca5a5;
                   border-radius:10px; padding:0.9rem 1.1rem; }
.action-high     { background:#fff7ed; border:1px solid #fdba74;
                   border-radius:10px; padding:0.9rem 1.1rem; }
.action-medium   { background:#fffbeb; border:1px solid #fcd34d;
                   border-radius:10px; padding:0.9rem 1.1rem; }
.action-low      { background:#f0fdf4; border:1px solid #86efac;
                   border-radius:10px; padding:0.9rem 1.1rem; }
.action-untrust  { background:#f9fafb; border:1px solid #d1d5db;
                   border-radius:10px; padding:0.9rem 1.1rem; }

/* ---------- demo case card ---------- */
.demo-card {
    background:#ffffff; border:1px solid #e4eaf4;
    border-radius:12px; padding:1rem 1.2rem;
    margin-bottom:0.7rem;
    box-shadow:0 2px 6px rgba(0,0,0,0.04);
}
.demo-id   { font-size:0.7rem; font-weight:700; text-transform:uppercase;
             letter-spacing:0.08em; color:#64748b; margin-bottom:4px; }
.demo-conf { font-size:0.82rem; font-weight:600; margin-bottom:6px; }
.demo-row  { display:flex; gap:24px; flex-wrap:wrap; }
.demo-field { font-size:0.78rem; }
.demo-field span { font-weight:600; color:#1e293b; }

/* ---------- capacity progress ---------- */
.cap-outer { background:#e2e8f0; border-radius:8px; height:10px; margin:6px 0; }
.cap-inner { background:#2563c7; border-radius:8px; height:10px; }

/* ---------- workflow step ---------- */
.wf-step {
    display:flex; gap:12px; align-items:flex-start;
    background:#ffffff; border:1px solid #e4eaf4;
    border-radius:10px; padding:0.7rem 1rem;
    margin-bottom:0.5rem;
    box-shadow:0 1px 4px rgba(0,0,0,0.03);
}
.wf-num {
    background:#2563c7; color:white; border-radius:50%;
    width:26px; height:26px; min-width:26px;
    display:flex; align-items:center; justify-content:center;
    font-size:0.75rem; font-weight:700;
}
.wf-text h5 { margin:0 0 2px 0; font-size:0.88rem;
              font-weight:600; color:#1e293b; }
.wf-text p  { margin:0; font-size:0.77rem; color:#64748b; }

/* ---------- stat row ---------- */
.stat-row  { display:flex; justify-content:space-between;
             padding:5px 0; border-bottom:1px solid #f1f5f9;
             font-size:0.82rem; }
.stat-row:last-child { border-bottom:none; }
.stat-key  { color:#64748b; }
.stat-val  { font-weight:700; color:#1e293b; }

/* ---------- summary panel ---------- */
.summary-panel {
    background:#ffffff; border:1px solid #e4eaf4;
    border-radius:12px; padding:1rem 1.2rem;
    box-shadow:0 2px 8px rgba(0,0,0,0.04);
}
.summary-panel h4 { margin:0 0 0.7rem 0; font-size:0.88rem;
                    font-weight:700; color:#1e293b; }
</style>
""", unsafe_allow_html=True)

# ---------------------------------------------------------------------------
# FILE PATHS  (unchanged)
# ---------------------------------------------------------------------------
ESCALATION_FILE = os.path.join("data", "escalation_results.csv")
CONFLICT_FILE   = os.path.join("data", "conflict_results.csv")
CLEANED_FILE    = os.path.join("data", "cleaned_maternal_data.csv")
TREND_FILE      = os.path.join("data", "trend_results.csv")
DEMO_FILE       = os.path.join("data", "demo_conflict_cases.csv")

# ---------------------------------------------------------------------------
# BACKEND HELPERS  (unchanged logic)
# ---------------------------------------------------------------------------

def load_csv(filepath):
    """Load a CSV safely; show warning and return None if missing."""
    if not os.path.exists(filepath):
        st.warning(
            "Required data file not found: `" + filepath + "`\n\n"
            "Please run the pipeline: generate_data.py → clean_data.py → "
            "risk_detection.py → trend_analysis.py → "
            "conflict_detection.py → escalation_workflow.py"
        )
        return None
    try:
        return pd.read_csv(filepath)
    except Exception as e:
        st.error("Error reading `" + filepath + "`: " + str(e))
        return None


def safe_get(series, key, default=0):
    """Return count for a key from a value_counts Series."""
    try:
        return int(series.get(key, default))
    except Exception:
        return default

# ---------------------------------------------------------------------------
# UI COMPONENT HELPERS
# ---------------------------------------------------------------------------

def kpi(label, value, sub, css_class):
    """Render one KPI card."""
    return (
        f'<div class="kpi-card {css_class}">'
        f'  <div class="kpi-label">{label}</div>'
        f'  <div class="kpi-value">{value}</div>'
        f'  <div class="kpi-sub">{sub}</div>'
        f'</div>'
    )


def kpi_row(*cards):
    """Wrap cards in kpi-grid div."""
    inner = "".join(cards)
    st.markdown(f'<div class="kpi-grid">{inner}</div>', unsafe_allow_html=True)


def section(title):
    st.markdown(f'<div class="sec-title">{title}</div>', unsafe_allow_html=True)


def badge(text, kind="untrust"):
    cls = {
        "critical": "b-critical", "high": "b-high",
        "medium": "b-medium",     "low": "b-low",
        "untrust": "b-untrust",   "conflict": "b-conflict",
        "sensor": "b-sensor",     "insuff": "b-insuff",
        "ok": "b-ok",
    }.get(kind, "b-untrust")
    return f'<span class="badge {cls}">{text}</span>'


def priority_badge(p):
    kind = {"CRITICAL":"critical","HIGH":"high","MEDIUM":"medium",
            "LOW":"low","UNTRUSTED":"untrust"}.get(str(p).upper(), "untrust")
    return badge(p, kind)


def conflict_badge(s):
    s_up = str(s).upper()
    if "SENSOR-SYMPTOM" in s_up:   return badge(s, "conflict")
    if "SENSOR-ONLY"    in s_up:   return badge(s, "sensor")
    if "INSUFFICIENT"   in s_up:   return badge(s, "insuff")
    return badge(s, "ok")


def dashboard_header(title_line1, title_line2, subtitle):
    st.markdown(
        f'<div class="dash-header">'
        f'  <h1>{title_line1}<br>{title_line2}</h1>'
        f'  <p>{subtitle}</p>'
        f'  <span class="status-badge">&#9679; SYSTEM ACTIVE</span>'
        f'  <div class="disclaimer-bar">'
        f'    Educational prototype using simulated and anonymous data. '
        f'    Not a medical diagnostic system.'
        f'  </div>'
        f'</div>',
        unsafe_allow_html=True,
    )


def sub_header(title, subtitle=""):
    sub = f'<p style="margin:2px 0 0 0;font-size:0.8rem;color:#64748b;">{subtitle}</p>' if subtitle else ""
    st.markdown(
        f'<div style="margin:0.2rem 0 0.9rem 0;">'
        f'  <h2 style="margin:0;font-size:1.15rem;font-weight:700;color:#0f2744;">{title}</h2>'
        f'  {sub}'
        f'</div>',
        unsafe_allow_html=True,
    )

# ---------------------------------------------------------------------------
# PAGE 1 – DASHBOARD
# ---------------------------------------------------------------------------

def show_dashboard():
    dashboard_header(
        "Remote Maternal Health Monitoring",
        "and Escalation System",
        "Remote monitoring, symptom reconciliation and safe escalation for simulated maternal health observations.",
    )

    df = load_csv(ESCALATION_FILE)
    if df is None:
        return

    total = len(df)
    p    = df["priority"].value_counts()        if "priority"        in df.columns else pd.Series()
    ep   = df["escalation_path"].value_counts() if "escalation_path" in df.columns else pd.Series()
    sfwd = df["store_forward_status"].value_counts() if "store_forward_status" in df.columns else pd.Series()
    comm = df["communication_result"].value_counts()  if "communication_result"  in df.columns else pd.Series()
    cap  = df["capacity_status"].value_counts()       if "capacity_status"       in df.columns else pd.Series()

    # ── KPI CARDS ───────────────────────────────────────────────────────────
    section("LIVE MONITORING OVERVIEW")
    kpi_row(
        kpi("Total Observations", total,                      "Simulated monitoring records", "kpi-total"),
        kpi("CRITICAL",           safe_get(p, "CRITICAL"),    "Urgent clinician review",      "kpi-critical"),
        kpi("HIGH",               safe_get(p, "HIGH"),        "Clinician review",             "kpi-high"),
        kpi("MEDIUM",             safe_get(p, "MEDIUM"),      "Scheduled follow-up",          "kpi-medium"),
        kpi("LOW",                safe_get(p, "LOW"),         "Continue monitoring",          "kpi-low"),
        kpi("UNTRUSTED",          safe_get(p, "UNTRUSTED"),   "Safe fallback",                "kpi-untrust"),
    )

    st.markdown("<br>", unsafe_allow_html=True)

    # ── RISK OVERVIEW ───────────────────────────────────────────────────────
    section("RISK OVERVIEW")
    col_chart, col_summary = st.columns([3, 2])

    with col_chart:
        if "priority" in df.columns:
            risk_data = (
                df["priority"]
                .value_counts()
                .reindex(["LOW","MEDIUM","HIGH","CRITICAL","UNTRUSTED"], fill_value=0)
            )
            st.bar_chart(risk_data, color="#2563c7", height=220)

    with col_summary:
        crit = safe_get(p, "CRITICAL")
        high = safe_get(p, "HIGH")
        unt  = safe_get(p, "UNTRUSTED")
        low  = safe_get(p, "LOW")
        med  = safe_get(p, "MEDIUM")
        st.markdown(
            f'<div class="summary-panel">'
            f'  <h4>Risk Monitoring</h4>'
            f'  <div class="stat-row"><span class="stat-key">Total observations</span>'
            f'    <span class="stat-val">{total}</span></div>'
            f'  <div class="stat-row"><span class="stat-key">Critical</span>'
            f'    <span class="stat-val" style="color:#dc2626;">{crit}</span></div>'
            f'  <div class="stat-row"><span class="stat-key">High</span>'
            f'    <span class="stat-val" style="color:#ea580c;">{high}</span></div>'
            f'  <div class="stat-row"><span class="stat-key">Medium</span>'
            f'    <span class="stat-val" style="color:#d97706;">{med}</span></div>'
            f'  <div class="stat-row"><span class="stat-key">Low</span>'
            f'    <span class="stat-val" style="color:#16a34a;">{low}</span></div>'
            f'  <div class="stat-row"><span class="stat-key">Untrusted</span>'
            f'    <span class="stat-val" style="color:#6b7280;">{unt}</span></div>'
            f'  <p style="margin-top:0.8rem;font-size:0.76rem;color:#64748b;">'
            f'    Critical and high-risk observations are routed for clinician review, '
            f'    while uncertain observations use the safe fallback pathway.'
            f'  </p>'
            f'</div>',
            unsafe_allow_html=True,
        )

    st.markdown("<br>", unsafe_allow_html=True)

    # ── ESCALATION PATHWAYS ─────────────────────────────────────────────────
    section("ESCALATION PATHWAYS")
    col_esc, col_cap = st.columns([3, 2])

    with col_esc:
        if "escalation_path" in df.columns:
            esc_data = df["escalation_path"].value_counts()
            st.bar_chart(esc_data, color="#16a34a", height=200)

    with col_cap:
        within  = safe_get(cap, "WITHIN_CAPACITY")
        queued  = safe_get(cap, "QUEUED")
        pct     = min(int((within / 10) * 100), 100)
        cm_val  = safe_get(ep, "CONTINUE_MONITORING")
        sf_val  = safe_get(ep, "SCHEDULE_FOLLOW_UP")
        cr_val  = safe_get(ep, "CLINICIAN_REVIEW")
        ucr_val = safe_get(ep, "URGENT_CLINICIAN_REVIEW")
        fb_val  = safe_get(ep, "SAFE_FALLBACK")

        st.markdown(
            f'<div class="summary-panel">'
            f'  <h4>Clinician Capacity</h4>'
            f'  <div class="stat-row"><span class="stat-key">Immediate capacity</span>'
            f'    <span class="stat-val">10 cases</span></div>'
            f'  <div class="stat-row"><span class="stat-key">Within capacity</span>'
            f'    <span class="stat-val">{within}</span></div>'
            f'  <div class="stat-row"><span class="stat-key">Queued cases</span>'
            f'    <span class="stat-val" style="color:#ea580c;">{queued}</span></div>'
            f'  <div class="cap-outer"><div class="cap-inner" style="width:{pct}%;"></div></div>'
            f'  <p style="font-size:0.72rem;color:#94a3b8;margin:4px 0 0.9rem 0;">'
            f'    {within}/10 immediate slots used</p>'
            f'  <h4 style="margin-bottom:0.5rem;">Pathway Distribution</h4>'
            f'  <div class="stat-row"><span class="stat-key">Continue Monitoring</span><span class="stat-val">{cm_val}</span></div>'
            f'  <div class="stat-row"><span class="stat-key">Schedule Follow-up</span><span class="stat-val">{sf_val}</span></div>'
            f'  <div class="stat-row"><span class="stat-key">Clinician Review</span><span class="stat-val">{cr_val}</span></div>'
            f'  <div class="stat-row"><span class="stat-key">Urgent Review</span><span class="stat-val" style="color:#dc2626;">{ucr_val}</span></div>'
            f'  <div class="stat-row"><span class="stat-key">Safe Fallback</span><span class="stat-val" style="color:#6b7280;">{fb_val}</span></div>'
            f'</div>',
            unsafe_allow_html=True,
        )

    st.markdown("<br>", unsafe_allow_html=True)

    # ── COMMUNICATION STATUS ────────────────────────────────────────────────
    section("COMMUNICATION STATUS")
    st.caption("📡 Offline support enabled — cases stored locally when internet is unavailable.")

    completed = safe_get(comm, "Clinician contact completed.")
    pending   = safe_get(comm, "Clinician contact pending.")
    failed    = safe_get(comm, "First communication attempt failed.")
    stored    = safe_get(sfwd, "STORED")

    kpi_row(
        kpi("Completed",         completed, "Clinician contacted",                "kpi-green"),
        kpi("Pending",           pending,   "Awaiting confirmation",              "kpi-blue"),
        kpi("Failed",            failed,    "First attempt failed",               "kpi-orange"),
        kpi("Stored for Forward",stored,    "Saved offline – forwarded on reconnect", "kpi-untrust"),
    )

    st.markdown("<br>", unsafe_allow_html=True)

    # ── SYSTEM FEATURES ─────────────────────────────────────────────────────
    section("SYSTEM FEATURES")
    f1, f2, f3, f4 = st.columns(4)
    features = [
        ("🔍", "Risk Detection",      "Rule-based baseline risk assessment using sensor readings and data quality flags."),
        ("📈", "Trend Analysis",       "Identifies increasing, decreasing and stable systolic BP trends across patient observations."),
        ("⚠️", "Conflict Detection",   "Reconciles sensor readings with patient-reported symptoms to catch mismatches."),
        ("🚨", "Escalation Workflow",  "Routes each case to the correct pathway based on priority, conflict status, and data reliability."),
    ]
    for col, (icon, title, desc) in zip([f1, f2, f3, f4], features):
        with col:
            st.markdown(
                f'<div class="info-card">'
                f'  <h4>{icon} {title}</h4>'
                f'  <p>{desc}</p>'
                f'</div>',
                unsafe_allow_html=True,
            )

    st.markdown("<br>", unsafe_allow_html=True)

    # ── PRIVACY CARD ────────────────────────────────────────────────────────
    section("PRIVACY & DATA GOVERNANCE")
    st.markdown(
        '<div class="privacy-card">'
        '  <h4>🔒 PRIVACY BY DESIGN</h4>'
        '  <div class="privacy-item">✓ &nbsp; Anonymous patient IDs only (P001–P100, DEMO001–DEMO006)</div>'
        '  <div class="privacy-item">✓ &nbsp; Simulated observations — no real clinical data</div>'
        '  <div class="privacy-item">✓ &nbsp; No names, phone numbers, or contact details</div>'
        '  <div class="privacy-item">✓ &nbsp; No real patient information stored or displayed</div>'
        '  <div class="privacy-item">✓ &nbsp; Minimal sensitive-data exposure — educational prototype only</div>'
        '</div>',
        unsafe_allow_html=True,
    )


# ---------------------------------------------------------------------------
# PAGE 2 – PATIENT MONITORING
# ---------------------------------------------------------------------------

def show_patient_monitoring():
    sub_header(
        "Patient Monitoring",
        "Select an anonymous patient ID to view their full observation history and latest vitals.",
    )

    df = load_csv(ESCALATION_FILE)
    if df is None:
        return

    if "patient_id" not in df.columns:
        st.warning("Column 'patient_id' not found.")
        return

    patient_ids = sorted(df["patient_id"].dropna().unique().tolist())

    sel_col, _ = st.columns([2, 5])
    with sel_col:
        selected_id = st.selectbox("Select Patient ID:", options=patient_ids)

    patient_df = df[df["patient_id"] == selected_id]
    if patient_df.empty:
        st.warning("No records found for patient " + selected_id + ".")
        return

    if "observation_day" in patient_df.columns:
        row = patient_df.sort_values("observation_day", ascending=False).iloc[0]
        history_df = patient_df.sort_values("observation_day", ascending=True)
    else:
        row = patient_df.iloc[-1]
        history_df = patient_df

    priority     = str(row.get("priority", ""))
    final_action = str(row.get("final_action", "N/A"))
    prio_up      = priority.upper()

    # ── Patient header card ─────────────────────────────────────────────────
    prio_color = {"CRITICAL":"#dc2626","HIGH":"#ea580c","MEDIUM":"#d97706",
                  "LOW":"#16a34a","UNTRUSTED":"#6b7280"}.get(prio_up, "#64748b")
    st.markdown(
        f'<div style="background:#0f2744;border-radius:12px;padding:1rem 1.4rem;'
        f'margin-bottom:1rem;display:flex;justify-content:space-between;align-items:center;">'
        f'  <div>'
        f'    <div style="font-size:0.7rem;color:#a8c4e8;text-transform:uppercase;'
        f'         letter-spacing:0.08em;font-weight:600;">Selected Patient</div>'
        f'    <div style="font-size:1.5rem;font-weight:800;color:white;">{selected_id}</div>'
        f'    <div style="font-size:0.8rem;color:#a8c4e8;">'
        f'      Week {row.get("pregnancy_week","N/A")} &nbsp;|&nbsp; '
        f'      Day {row.get("observation_day","N/A")} &nbsp;|&nbsp; '
        f'      Quality: {row.get("data_quality","N/A")}'
        f'    </div>'
        f'  </div>'
        f'  <div style="text-align:right;">'
        f'    <div style="font-size:0.7rem;color:#a8c4e8;margin-bottom:4px;">Priority</div>'
        f'    <div style="font-size:1.3rem;font-weight:800;color:{prio_color};">{priority}</div>'
        f'  </div>'
        f'</div>',
        unsafe_allow_html=True,
    )

    # ── Tabs ────────────────────────────────────────────────────────────────
    tab_vitals, tab_symptoms, tab_workflow, tab_history = st.tabs([
        "Vital Signs", "Symptoms", "Risk & Escalation", "Observation History"
    ])

    # -- VITAL SIGNS --
    with tab_vitals:
        section("SENSOR READINGS — LATEST OBSERVATION")
        v1, v2, v3, v4, v5 = st.columns(5)

        def vital_box(col, label, val, unit):
            with col:
                st.markdown(
                    f'<div class="vital-box">'
                    f'  <div class="vital-label">{label}</div>'
                    f'  <div class="vital-value">{val}</div>'
                    f'  <div class="vital-unit">{unit}</div>'
                    f'</div>',
                    unsafe_allow_html=True,
                )

        vital_box(v1, "Systolic BP",  str(row.get("systolic_bp",  "N/A")), "mmHg")
        vital_box(v2, "Diastolic BP", str(row.get("diastolic_bp", "N/A")), "mmHg")
        vital_box(v3, "Heart Rate",   str(row.get("heart_rate",   "N/A")), "bpm")
        vital_box(v4, "Temperature",  str(row.get("temperature",  "N/A")), "°C")
        vital_box(v5, "SpO₂",         str(row.get("spo2",         "N/A")), "%")

        # BP trend chart
        section("SYSTOLIC BP TREND")
        bp_data = history_df[["observation_day", "systolic_bp"]].dropna() \
            if all(c in history_df.columns for c in ["observation_day","systolic_bp"]) \
            else pd.DataFrame()
        if not bp_data.empty:
            bp_idx = bp_data.set_index("observation_day")
            bp_idx.index = bp_idx.index.astype(str)
            st.line_chart(bp_idx, color="#dc2626", height=180)
            st.caption("Systolic BP (mmHg) across all observation days. Rising trends may indicate increasing risk.")
        else:
            st.info("No valid systolic BP readings available for chart.")

    # -- SYMPTOMS --
    with tab_symptoms:
        section("PATIENT-REPORTED SYMPTOMS")
        symptom_map = [
            ("headache",               "Headache"),
            ("blurred_vision",         "Blurred Vision"),
            ("bleeding",               "Bleeding"),
            ("abdominal_pain",         "Abdominal Pain"),
            ("swelling",               "Swelling"),
            ("reduced_fetal_movement", "Reduced Fetal Movement"),
        ]
        sym_html = '<div style="display:flex;flex-wrap:wrap;gap:10px;margin-top:0.4rem;">'
        any_yes = False
        for col_name, label in symptom_map:
            val = str(row.get(col_name, "No"))
            if val == "Yes":
                sym_html += f'<div><div class="vital-label">{label}</div><span class="sym-yes">⚠ {label}</span></div>'
                any_yes = True
            else:
                sym_html += f'<div><div class="vital-label">{label}</div><span class="sym-no">✓ No {label}</span></div>'
        sym_html += "</div>"
        st.markdown(sym_html, unsafe_allow_html=True)

        if any_yes:
            st.warning("One or more concerning symptoms reported. Review conflict status tab.")
        else:
            st.success("No concerning symptoms reported for this observation.")

    # -- RISK & ESCALATION --
    with tab_workflow:
        section("RISK ASSESSMENT")
        r1, r2, r3 = st.columns(3)
        with r1: st.markdown(f'<div class="info-card"><h4>Risk Level</h4>'
                             f'<p style="font-size:1.2rem;font-weight:800;color:#0f2744;">'
                             f'{row.get("risk_level","N/A")}</p></div>', unsafe_allow_html=True)
        with r2: st.markdown(f'<div class="info-card"><h4>Trend Status</h4>'
                             f'<p style="font-size:1.1rem;font-weight:700;color:#0f2744;">'
                             f'{row.get("trend_status","N/A")}</p></div>', unsafe_allow_html=True)
        with r3: st.markdown(f'<div class="info-card"><h4>Data Quality</h4>'
                             f'<p style="font-size:1.1rem;font-weight:700;color:#0f2744;">'
                             f'{row.get("data_quality","N/A")}</p></div>', unsafe_allow_html=True)

        st.markdown("<br>", unsafe_allow_html=True)
        section("CONFLICT & ESCALATION")
        e1, e2, e3, e4 = st.columns(4)
        conf_s = str(row.get("conflict_status", "N/A"))
        prio_s = str(row.get("priority", "N/A"))
        with e1:
            st.markdown("**Conflict Status**")
            st.markdown(conflict_badge(conf_s), unsafe_allow_html=True)
        with e2:
            st.markdown("**Priority**")
            st.markdown(priority_badge(prio_s), unsafe_allow_html=True)
        with e3:
            st.markdown("**Escalation Pathway**")
            st.write(str(row.get("escalation_path", "N/A")))
        with e4:
            st.markdown("**Schedule Status**")
            st.write(str(row.get("schedule_status", "N/A")))

        st.markdown("<br>", unsafe_allow_html=True)
        section("FINAL ESCALATION ACTION")
        action_cls = {
            "CRITICAL":"action-critical","HIGH":"action-high",
            "MEDIUM":"action-medium","LOW":"action-low","UNTRUSTED":"action-untrust",
        }.get(prio_up, "action-untrust")
        st.markdown(
            f'<div class="{action_cls}">'
            f'  <div style="font-size:0.72rem;font-weight:700;text-transform:uppercase;'
            f'       letter-spacing:0.06em;color:#64748b;margin-bottom:4px;">Recommended Action</div>'
            f'  <div style="font-size:1.05rem;font-weight:700;color:#1e293b;">{final_action}</div>'
            f'  <div style="font-size:0.75rem;color:#64748b;margin-top:4px;">'
            f'    Store-Forward: {row.get("store_forward_status","N/A")} &nbsp;|&nbsp; '
            f'    Communication: {row.get("communication_result","N/A")}'
            f'  </div>'
            f'</div>',
            unsafe_allow_html=True,
        )

    # -- HISTORY TABLE --
    with tab_history:
        section("ALL OBSERVATIONS — " + selected_id)
        history_cols = [
            "observation_day","pregnancy_week","systolic_bp","diastolic_bp",
            "heart_rate","data_quality","risk_level","trend_status",
            "conflict_status","priority","escalation_path","final_action",
        ]
        history_cols = [c for c in history_cols if c in df.columns]
        st.dataframe(history_df[history_cols], use_container_width=True, hide_index=True)


# ---------------------------------------------------------------------------
# PAGE 3 – CONFLICT CASES
# ---------------------------------------------------------------------------

def show_conflict_cases():
    sub_header(
        "Conflict Cases",
        "Phase 6 conflict detection checks whether sensor readings and patient-reported symptoms agree.",
    )

    df = load_csv(CONFLICT_FILE)
    if df is None:
        return

    cs = df["conflict_status"].value_counts() if "conflict_status" in df.columns else pd.Series()

    # ── Summary KPIs ─────────────────────────────────────────────────────
    section("CONFLICT SUMMARY")
    kpi_row(
        kpi("Total Cases",            len(df),                                   "All processed observations", "kpi-total"),
        kpi("Sensor-Symptom Conflict",safe_get(cs,"SENSOR-SYMPTOM CONFLICT"),   "Sensor vs symptoms mismatch","kpi-critical"),
        kpi("Sensor-Only Concern",    safe_get(cs,"SENSOR-ONLY CONCERN"),       "Abnormal sensor, no symptoms","kpi-high"),
        kpi("Symptom-Only Concern",   safe_get(cs,"SYMPTOM-ONLY CONCERN"),      "Symptoms, normal sensor",    "kpi-medium"),
        kpi("Insufficient Data",      safe_get(cs,"INSUFFICIENT DATA"),         "Data quality too poor",      "kpi-untrust"),
    )

    st.markdown("<br>", unsafe_allow_html=True)

    # ── Conflict type guide ──────────────────────────────────────────────
    section("CONFLICT TYPE GUIDE")
    g1, g2, g3, g4 = st.columns(4)
    guides = [
        ("b-conflict","SENSOR-SYMPTOM CONFLICT",
         "Sensor shows LOW/MEDIUM risk but patient reports concerning symptoms. Symptoms take priority over sensor."),
        ("b-sensor",  "SENSOR-ONLY CONCERN",
         "Sensor shows HIGH/CRITICAL risk but no symptoms reported. Sensor reading is NOT dismissed."),
        ("b-insuff",  "INSUFFICIENT DATA",
         "Data quality is too poor to reliably assess. Routes to SAFE FALLBACK — never classified as LOW."),
        ("b-ok",      "NO CONFLICT",
         "Sensor and symptoms both agree. Routine monitoring can continue as normal."),
    ]
    for col, (cls, title, desc) in zip([g1,g2,g3,g4], guides):
        with col:
            st.markdown(
                f'<div class="info-card">'
                f'  <span class="badge {cls}" style="margin-bottom:8px;display:inline-block;">{title}</span>'
                f'  <p>{desc}</p>'
                f'</div>',
                unsafe_allow_html=True,
            )

    st.markdown("<br>", unsafe_allow_html=True)

    # ── Conflict cases table ──────────────────────────────────────────────
    section("FLAGGED CASES TABLE")
    conflict_display_cols = [
        "patient_id","risk_level","concerning_symptoms",
        "trend_status","conflict_status","conflict_reason","final_workflow_action",
    ]
    conflict_display_cols = [c for c in conflict_display_cols if c in df.columns]

    if "conflict_status" in df.columns:
        conflict_only = df[df["conflict_status"] != "NO CONFLICT"]
    else:
        conflict_only = df

    no_conflict_count = safe_get(cs, "NO CONFLICT")
    st.caption(
        "Showing **" + str(len(conflict_only)) + "** flagged records — "
        "excludes " + str(no_conflict_count) + " routine NO CONFLICT records."
    )
    st.dataframe(conflict_only[conflict_display_cols], use_container_width=True, hide_index=True)

    st.markdown("<br>", unsafe_allow_html=True)

    # ── Demo cases ───────────────────────────────────────────────────────
    section("SIMULATED DEMONSTRATION CASES")
    st.error(
        "SIMULATED DEMONSTRATION CASES — NOT REAL PATIENTS\n\n"
        "DEMO001–DEMO006 are hand-crafted to cover every conflict detection and "
        "escalation scenario. They are entirely fictional."
    )

    demo_df = load_csv(DEMO_FILE)
    if demo_df is None:
        return

    demo_meta = {
        "DEMO001": ("SENSOR-SYMPTOM CONFLICT", "b-conflict", "LOW",   "Headache + Blurred Vision", "CLINICIAN_REVIEW"),
        "DEMO002": ("SENSOR-ONLY CONCERN",      "b-sensor",  "HIGH",  "None reported",             "CLINICIAN_REVIEW"),
        "DEMO003": ("NO CONFLICT (both high)",  "b-conflict","HIGH",  "Headache + Blurred Vision", "URGENT_CLINICIAN_REVIEW"),
        "DEMO004": ("INSUFFICIENT DATA",        "b-insuff",  "UNCERTAIN","None",                   "SAFE_FALLBACK"),
        "DEMO005": ("NO CONFLICT",              "b-ok",      "LOW",   "None",                      "CONTINUE_MONITORING"),
        "DEMO006": ("NO CONFLICT (offline)",    "b-sensor",  "HIGH",  "Headache + Blurred Vision", "URGENT_CLINICIAN_REVIEW"),
    }
    demo_explanations = {
        "DEMO001": "LOW sensor risk + headache + blurred vision → symptoms take priority → CLINICIAN REVIEW.",
        "DEMO002": "HIGH sensor risk + no symptoms → sensor NOT dismissed → CLINICIAN REVIEW.",
        "DEMO003": "HIGH sensor risk + headache + blurred vision → both concerning → URGENT CLINICIAN REVIEW.",
        "DEMO004": "UNCERTAIN risk + incomplete data + offline → SAFE FALLBACK. Never classified as LOW.",
        "DEMO005": "LOW sensor risk + no symptoms + good quality → NO CONFLICT → CONTINUE MONITORING.",
        "DEMO006": "HIGH sensor risk + symptoms + OFFLINE → CRITICAL + store-and-forward → URGENT REVIEW.",
    }

    for _, row in demo_df.iterrows():
        pid      = str(row.get("patient_id", ""))
        risk     = str(row.get("risk_level",  "N/A"))
        internet = str(row.get("internet_status", "N/A"))
        comm     = str(row.get("communication_status", "N/A"))
        conf_label, conf_cls, _, syms, action = demo_meta.get(
            pid, ("UNKNOWN","b-untrust","N/A","N/A","N/A")
        )
        explanation = demo_explanations.get(pid, "")

        with st.expander(pid + "  —  " + conf_label + "  |  Internet: " + internet):
            st.markdown(
                f'<div style="margin-bottom:0.6rem;">'
                f'  <div class="demo-id">{pid}</div>'
                f'  <span class="badge {conf_cls}">{conf_label}</span>'
                f'</div>'
                f'<div class="demo-row">'
                f'  <div class="demo-field">Sensor Risk: <span>{risk}</span></div>'
                f'  <div class="demo-field">Symptoms: <span>{syms}</span></div>'
                f'  <div class="demo-field">Internet: <span>{internet}</span></div>'
                f'  <div class="demo-field">Communication: <span>{comm}</span></div>'
                f'  <div class="demo-field">Action: <span>{action}</span></div>'
                f'</div>',
                unsafe_allow_html=True,
            )
            st.info(explanation)

            dc1, dc2 = st.columns(2)
            with dc1:
                st.markdown("**Sensor Readings**")
                for field, label in [
                    ("systolic_bp","Systolic BP"),("diastolic_bp","Diastolic BP"),
                    ("heart_rate","Heart Rate"),("temperature","Temperature"),("spo2","SpO₂"),
                    ("data_quality","Data Quality"),
                ]:
                    st.write(f"{label}: {row.get(field,'N/A')}")
            with dc2:
                st.markdown("**Symptoms**")
                for col_name, label in [
                    ("headache","Headache"),("blurred_vision","Blurred Vision"),
                    ("bleeding","Bleeding"),("abdominal_pain","Abdominal Pain"),
                    ("swelling","Swelling"),("reduced_fetal_movement","Reduced Fetal Movement"),
                ]:
                    val = str(row.get(col_name,"No"))
                    if val == "Yes":
                        st.markdown(f'<span class="sym-yes">⚠ {label}</span>', unsafe_allow_html=True)
                    else:
                        st.markdown(f'<span class="sym-no">✓ No {label}</span>', unsafe_allow_html=True)
                    st.markdown("&nbsp;", unsafe_allow_html=True)


# ---------------------------------------------------------------------------
# PAGE 4 – ESCALATION QUEUE
# ---------------------------------------------------------------------------

def show_escalation_queue():
    sub_header(
        "Escalation Queue",
        "All observations sorted by priority. Clinician capacity: 10 HIGH/CRITICAL cases per review cycle.",
    )

    df = load_csv(ESCALATION_FILE)
    if df is None:
        return

    p   = df["priority"].value_counts()        if "priority"        in df.columns else pd.Series()
    cap = df["capacity_status"].value_counts()  if "capacity_status" in df.columns else pd.Series()

    # ── Priority KPIs ─────────────────────────────────────────────────────
    section("PRIORITY OVERVIEW")
    kpi_row(
        kpi("CRITICAL",  safe_get(p,"CRITICAL"),  "Urgent review required", "kpi-critical"),
        kpi("HIGH",      safe_get(p,"HIGH"),      "Clinician review",       "kpi-high"),
        kpi("MEDIUM",    safe_get(p,"MEDIUM"),    "Scheduled follow-up",    "kpi-medium"),
        kpi("LOW",       safe_get(p,"LOW"),       "Continue monitoring",    "kpi-low"),
        kpi("UNTRUSTED", safe_get(p,"UNTRUSTED"), "Safe fallback",          "kpi-untrust"),
    )

    st.markdown("<br>", unsafe_allow_html=True)

    # ── Clinician capacity ───────────────────────────────────────────────
    section("CLINICIAN CAPACITY")
    within = safe_get(cap,"WITHIN_CAPACITY")
    queued = safe_get(cap,"QUEUED")
    pct    = min(int((within / 10) * 100), 100)

    cc1, cc2, cc3, cc4 = st.columns([1,1,1,3])
    with cc1:
        st.markdown(
            '<div class="kpi-card kpi-blue"><div class="kpi-label">Capacity Limit</div>'
            '<div class="kpi-value">10</div>'
            '<div class="kpi-sub">Cases per cycle</div></div>',
            unsafe_allow_html=True,
        )
    with cc2:
        st.markdown(
            f'<div class="kpi-card kpi-green"><div class="kpi-label">Within Capacity</div>'
            f'<div class="kpi-value">{within}</div>'
            f'<div class="kpi-sub">Immediate review</div></div>',
            unsafe_allow_html=True,
        )
    with cc3:
        st.markdown(
            f'<div class="kpi-card kpi-orange"><div class="kpi-label">Queued</div>'
            f'<div class="kpi-value">{queued}</div>'
            f'<div class="kpi-sub">Next available slot</div></div>',
            unsafe_allow_html=True,
        )
    with cc4:
        st.markdown(
            f'<div style="padding:0.9rem 1rem;background:#f8faff;border:1px solid #dbe8f8;'
            f'border-radius:12px;height:100%;">'
            f'  <div style="font-size:0.8rem;font-weight:600;color:#0f2744;margin-bottom:6px;">'
            f'    Immediate Capacity Utilisation: {within}/10 slots</div>'
            f'  <div class="cap-outer"><div class="cap-inner" style="width:{pct}%;"></div></div>'
            f'  <div style="font-size:0.74rem;color:#64748b;margin-top:6px;">'
            f'    First 10 eligible HIGH/CRITICAL cases = immediate review. '
            f'    Remaining {queued} cases queued for next available slot. '
            f'    Cases are NEVER discarded — priority is preserved in the queue.</div>'
            f'</div>',
            unsafe_allow_html=True,
        )

    st.markdown("<br>", unsafe_allow_html=True)

    # ── Priority tabs ────────────────────────────────────────────────────
    if "priority" in df.columns:
        critical_df = df[df["priority"] == "CRITICAL"].copy()
        high_df     = df[df["priority"] == "HIGH"].copy()

        high_crit_cols = [c for c in [
            "patient_id","observation_day","risk_level","conflict_status",
            "escalation_path","schedule_status","capacity_status",
            "communication_result","store_forward_status","final_action",
        ] if c in df.columns]

        tab_crit, tab_high = st.tabs([
            "🔴 CRITICAL  (" + str(len(critical_df)) + " cases)",
            "🟠 HIGH  ("     + str(len(high_df))     + " cases)",
        ])
        with tab_crit:
            if not critical_df.empty:
                st.dataframe(critical_df[high_crit_cols], use_container_width=True, hide_index=True)
            else:
                st.info("No CRITICAL priority cases.")
        with tab_high:
            if not high_df.empty:
                st.dataframe(high_df[high_crit_cols], use_container_width=True, hide_index=True)
            else:
                st.info("No HIGH priority cases.")

    st.markdown("<br>", unsafe_allow_html=True)

    # ── Full queue with filter ────────────────────────────────────────────
    section("FULL ESCALATION QUEUE")

    priority_order = {"CRITICAL":0,"HIGH":1,"UNTRUSTED":2,"MEDIUM":3,"LOW":4}
    sorted_df = df.copy()
    if "priority" in sorted_df.columns:
        sorted_df["_sk"] = sorted_df["priority"].map(lambda x: priority_order.get(str(x),99))
        sorted_df = sorted_df.sort_values("_sk").drop(columns=["_sk"])

    display_cols = [c for c in [
        "patient_id","priority","escalation_path","schedule_status",
        "capacity_status","communication_result","store_forward_status","final_action",
    ] if c in sorted_df.columns]

    fc, _ = st.columns([3,4])
    with fc:
        sel_p = st.multiselect(
            "Filter by priority:",
            options=["CRITICAL","HIGH","UNTRUSTED","MEDIUM","LOW"],
            default=["CRITICAL","HIGH","UNTRUSTED"],
        )

    filtered = sorted_df[sorted_df["priority"].isin(sel_p)] \
        if sel_p and "priority" in sorted_df.columns else sorted_df

    st.caption(
        "Showing **" + str(len(filtered)) + "** of **" + str(len(df)) +
        "** records, sorted most urgent first."
    )
    st.dataframe(filtered[display_cols], use_container_width=True, hide_index=True)


# ---------------------------------------------------------------------------
# PAGE 5 – SYSTEM SUMMARY
# ---------------------------------------------------------------------------

def show_system_summary():
    sub_header(
        "System Summary",
        "High-level overview of the Remote Maternal Health Monitoring and Escalation System prototype.",
    )

    # ── Workflow steps ────────────────────────────────────────────────────
    section("SYSTEM WORKFLOW  —  PHASE 2–7 PIPELINE")
    steps = [
        ("2","Data Generation",   "generate_data.py",      "994 simulated anonymous patient records created"),
        ("3","Data Cleaning",     "clean_data.py",          "Records flagged as Good / Incomplete / Invalid"),
        ("4","Risk Detection",    "risk_detection.py",      "LOW / MEDIUM / HIGH / CRITICAL / UNCERTAIN risk assigned"),
        ("5","Trend Analysis",    "trend_analysis.py",      "Systolic BP trend detected per patient"),
        ("6","Conflict Detection","conflict_detection.py",  "Sensor-symptom mismatches flagged"),
        ("7","Escalation",        "escalation_workflow.py", "Cases routed to 5 escalation pathways"),
        ("8","Dashboard",         "app.py",                 "Results visualised in this Streamlit dashboard"),
    ]
    wf_col1, wf_col2 = st.columns(2)
    for i, (num, title, module, detail) in enumerate(steps):
        target = wf_col1 if i % 2 == 0 else wf_col2
        with target:
            st.markdown(
                f'<div class="wf-step">'
                f'  <div class="wf-num">{num}</div>'
                f'  <div class="wf-text">'
                f'    <h5>{title} <code style="font-size:0.72rem;color:#64748b;">{module}</code></h5>'
                f'    <p>{detail}</p>'
                f'  </div>'
                f'</div>',
                unsafe_allow_html=True,
            )

    st.markdown("<br>", unsafe_allow_html=True)

    # ── Dataset statistics panels ──────────────────────────────────────────
    section("DATASET STATISTICS")
    d1, d2, d3, d4 = st.columns(4)

    with d1:
        st.markdown(
            '<div class="summary-panel"><h4>Dataset</h4>'
            '<div class="stat-row"><span class="stat-key">Total observations</span><span class="stat-val">994</span></div>'
            '<div class="stat-row"><span class="stat-key">Unique patients</span><span class="stat-val">100</span></div>'
            '<div class="stat-row"><span class="stat-key">Avg per patient</span><span class="stat-val">~10</span></div>'
            '</div>',
            unsafe_allow_html=True,
        )

    with d2:
        st.markdown(
            '<div class="summary-panel"><h4>Data Quality</h4>'
            '<div class="stat-row"><span class="stat-key">Good</span><span class="stat-val" style="color:#16a34a;">818</span></div>'
            '<div class="stat-row"><span class="stat-key">Incomplete</span><span class="stat-val" style="color:#d97706;">151</span></div>'
            '<div class="stat-row"><span class="stat-key">Invalid</span><span class="stat-val" style="color:#dc2626;">25</span></div>'
            '<div class="stat-row"><span class="stat-key">Missing values</span><span class="stat-val">280</span></div>'
            '</div>',
            unsafe_allow_html=True,
        )

    with d3:
        # Live from trend CSV
        trend_df = load_csv(TREND_FILE)
        if trend_df is not None and "overall_trend" in trend_df.columns:
            tv = trend_df["overall_trend"].value_counts()
            inc  = int(tv.get("Consistently Increasing", 0))
            dec  = int(tv.get("Consistently Decreasing", 0))
            stab = int(tv.get("Stable/Variable", 0))
        else:
            inc = dec = stab = 0
        st.markdown(
            f'<div class="summary-panel"><h4>BP Trends (100 patients)</h4>'
            f'<div class="stat-row"><span class="stat-key">Increasing</span><span class="stat-val" style="color:#dc2626;">{inc}</span></div>'
            f'<div class="stat-row"><span class="stat-key">Decreasing</span><span class="stat-val" style="color:#16a34a;">{dec}</span></div>'
            f'<div class="stat-row"><span class="stat-key">Stable/Variable</span><span class="stat-val">{stab}</span></div>'
            f'</div>',
            unsafe_allow_html=True,
        )

    with d4:
        # Live from escalation CSV
        esc_df = load_csv(ESCALATION_FILE)
        if esc_df is not None and "communication_result" in esc_df.columns:
            cv = esc_df["communication_result"].value_counts()
            comp  = int(cv.get("Clinician contact completed.", 0))
            pend  = int(cv.get("Clinician contact pending.", 0))
            fail  = int(cv.get("First communication attempt failed.", 0))
        else:
            comp = pend = fail = 0
        sf_df = esc_df if esc_df is not None else pd.DataFrame()
        stored = int(sf_df["store_forward_status"].value_counts().get("STORED", 0)) \
            if esc_df is not None and "store_forward_status" in sf_df.columns else 0
        st.markdown(
            f'<div class="summary-panel"><h4>Communication</h4>'
            f'<div class="stat-row"><span class="stat-key">Completed</span><span class="stat-val" style="color:#16a34a;">{comp}</span></div>'
            f'<div class="stat-row"><span class="stat-key">Pending</span><span class="stat-val">{pend}</span></div>'
            f'<div class="stat-row"><span class="stat-key">Failed</span><span class="stat-val" style="color:#ea580c;">{fail}</span></div>'
            f'<div class="stat-row"><span class="stat-key">Stored (offline)</span><span class="stat-val" style="color:#6b7280;">{stored}</span></div>'
            f'</div>',
            unsafe_allow_html=True,
        )

    st.markdown("<br>", unsafe_allow_html=True)

    # ── Phase result tabs ─────────────────────────────────────────────────
    section("PHASE-BY-PHASE LIVE RESULTS")
    t4, t5, t6, t7 = st.tabs([
        "Phase 4 – Risk","Phase 5 – Trend","Phase 6 – Conflict","Phase 7 – Escalation"
    ])

    with t4:
        risk_df = load_csv(os.path.join("data","baseline_risk_results.csv"))
        if risk_df is not None and "risk_level" in risk_df.columns:
            cl, cr = st.columns(2)
            with cl:
                rc = risk_df["risk_level"].value_counts().reset_index()
                rc.columns = ["Risk Level","Count"]
                st.dataframe(rc, use_container_width=True, hide_index=True)
            with cr:
                st.bar_chart(
                    risk_df["risk_level"].value_counts()
                    .reindex(["CRITICAL","HIGH","MEDIUM","LOW","UNCERTAIN"],fill_value=0),
                    color="#2563c7", height=200,
                )

    with t5:
        if trend_df is not None and "overall_trend" in trend_df.columns:
            cl, cr = st.columns(2)
            with cl:
                tc = trend_df["overall_trend"].value_counts().reset_index()
                tc.columns = ["Trend","Count"]
                st.dataframe(tc, use_container_width=True, hide_index=True)
            with cr:
                st.bar_chart(trend_df["overall_trend"].value_counts(), color="#16a34a", height=200)

    with t6:
        cf_df = load_csv(CONFLICT_FILE)
        if cf_df is not None and "conflict_status" in cf_df.columns:
            cl, cr = st.columns(2)
            with cl:
                cc = cf_df["conflict_status"].value_counts().reset_index()
                cc.columns = ["Conflict Status","Count"]
                st.dataframe(cc, use_container_width=True, hide_index=True)
            with cr:
                st.bar_chart(cf_df["conflict_status"].value_counts(), color="#ea580c", height=200)

    with t7:
        if esc_df is not None and "escalation_path" in esc_df.columns:
            cl, cr = st.columns(2)
            with cl:
                ec = esc_df["escalation_path"].value_counts().reset_index()
                ec.columns = ["Escalation Path","Count"]
                st.dataframe(ec, use_container_width=True, hide_index=True)
            with cr:
                st.bar_chart(esc_df["escalation_path"].value_counts(), color="#8b5cf6", height=200)

    st.markdown("<br>", unsafe_allow_html=True)

    # ── Module table ──────────────────────────────────────────────────────
    section("PROJECT MODULES")
    module_data = {
        "Phase": ["2","3","4","5","6","7","8"],
        "Module": [
            "generate_data.py","clean_data.py","risk_detection.py",
            "trend_analysis.py","conflict_detection.py",
            "escalation_workflow.py","app.py",
        ],
        "Purpose": [
            "Generates 994 simulated anonymous patient records",
            "Flags records as Good / Incomplete / Invalid",
            "Assigns LOW / MEDIUM / HIGH / UNCERTAIN risk level",
            "Detects systolic BP trends across patient observations",
            "Detects sensor-symptom mismatches",
            "Routes cases to the correct escalation pathway",
            "Streamlit monitoring dashboard (this file)",
        ],
    }
    st.dataframe(pd.DataFrame(module_data), use_container_width=True, hide_index=True)

    st.markdown("<br>", unsafe_allow_html=True)

    # ── Privacy & disclaimer ──────────────────────────────────────────────
    st.markdown(
        '<div class="privacy-card">'
        '  <h4>🔒 PRIVACY BY DESIGN</h4>'
        '  <div class="privacy-item">✓ &nbsp; Anonymous patient IDs — P001–P100 and DEMO001–DEMO006</div>'
        '  <div class="privacy-item">✓ &nbsp; All 994 records are entirely simulated — no real patients</div>'
        '  <div class="privacy-item">✓ &nbsp; No names, phone numbers, addresses, or contact details</div>'
        '  <div class="privacy-item">✓ &nbsp; This system is NOT a medical diagnostic tool</div>'
        '  <div class="privacy-item">✓ &nbsp; Do NOT use for real clinical decisions</div>'
        '</div>',
        unsafe_allow_html=True,
    )


# ---------------------------------------------------------------------------
# SIDEBAR + MAIN ROUTING
# ---------------------------------------------------------------------------

def main():
    # ── Sidebar brand ──────────────────────────────────────────────────────
    st.sidebar.markdown(
        '<div style="text-align:center;padding:1.2rem 0 0.6rem 0;">'
        '  <div style="font-size:2.2rem;">🏥</div>'
        '  <div style="font-size:0.95rem;font-weight:800;letter-spacing:0.04em;'
        '       color:white;margin-top:4px;">MATERNAL MONITOR</div>'
        '  <div style="font-size:0.68rem;color:#7aa8d8;margin-top:2px;">'
        '    Phase 8 — Streamlit Prototype</div>'
        '</div>',
        unsafe_allow_html=True,
    )
    st.sidebar.divider()

    # ── Navigation ────────────────────────────────────────────────────────
    nav_options = {
        "🏠  Dashboard":           "Dashboard",
        "👩‍⚕️  Patient Monitoring":  "Patient Monitoring",
        "⚠️  Conflict Cases":       "Conflict Cases",
        "🚨  Escalation Queue":     "Escalation Queue",
        "📊  System Summary":       "System Summary",
    }
    choice = st.sidebar.radio(
        "Navigation",
        list(nav_options.keys()),
        label_visibility="collapsed",
    )
    page = nav_options[choice]

    st.sidebar.divider()

    # ── System status ─────────────────────────────────────────────────────
    st.sidebar.markdown(
        '<div style="padding:0.5rem 0;">'
        '  <div style="font-size:0.68rem;font-weight:700;text-transform:uppercase;'
        '       letter-spacing:0.08em;color:#7aa8d8;margin-bottom:6px;">SYSTEM STATUS</div>'
        '  <div style="font-size:0.82rem;color:white;">🟢 &nbsp; Monitoring Active</div>'
        '</div>',
        unsafe_allow_html=True,
    )

    st.sidebar.divider()

    # ── Privacy notice ────────────────────────────────────────────────────
    st.sidebar.markdown(
        '<div style="padding:0.5rem 0;">'
        '  <div style="font-size:0.68rem;font-weight:700;text-transform:uppercase;'
        '       letter-spacing:0.08em;color:#7aa8d8;margin-bottom:6px;">PRIVACY</div>'
        '  <div style="font-size:0.78rem;color:#c8d8ec;line-height:1.7;">'
        '    ✓ Anonymous IDs<br>'
        '    ✓ Simulated Data<br>'
        '    ✓ No Real Patient Data'
        '  </div>'
        '</div>',
        unsafe_allow_html=True,
    )

    st.sidebar.markdown("<br>", unsafe_allow_html=True)
    st.sidebar.warning(
        "Educational prototype only.\nNOT a medical diagnostic system.\n"
        "Do NOT use for real clinical decisions."
    )

    # ── Route ─────────────────────────────────────────────────────────────
    if page == "Dashboard":
        show_dashboard()
    elif page == "Patient Monitoring":
        show_patient_monitoring()
    elif page == "Conflict Cases":
        show_conflict_cases()
    elif page == "Escalation Queue":
        show_escalation_queue()
    elif page == "System Summary":
        show_system_summary()


# ---------------------------------------------------------------------------
# ENTRY POINT
# ---------------------------------------------------------------------------
if __name__ == "__main__":
    main()
